server:
  port: 7002 #???
eureka:
  instance:
    hostname: myeureka7002.com #Eureka Server ????
  client:
    register-with-eureka: false #false ?????????????
    fetch-registry: false  #false ??????????????????????????????????
    service-url:
      defaultZone: http://myeureka7001.com:7001/eureka/,http://myeureka7003.com:7003/eureka/ #??? Eureka Server ??? 7001 ? 7003 ?