server:
  port: 80 #???
############################################# Spring Cloud Ribbon ??????##########################
eureka:
  client:
    register-with-eureka: false #??????????????????????????
    fetch-registry: true  #????????????????????????
    service-url:
      defaultZone: http://myeureka7001.com:7001/eureka/,http://myeureka7002.com:7002/eureka/,http://myeureka7003.com:7003/eureka/ #????????