server:
  port: 7001  #???
eureka:
  instance:
    hostname: myeureka7001.com #eureka????????
  client:
    register-with-eureka: false #false ?????????????
    fetch-registry: false #false ??????????????????????????????????
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #???
      defaultZone: http://myeureka7002.com:7002/eureka/,http://myeureka7003.com:7003/eureka/ #??? ???? Eureka Server ??? 7003 ? 7003 ??????????? Eureka Server ??