server:
  port: 7003 #???
eureka:
  instance:
    hostname: myeureka7003.com #Eureka Server ????
  client:
    register-with-eureka: false #false ?????????????
    fetch-registry: false  #false ??????????????????????????????????
    service-url:
      defaultZone: http://myeureka7001.com:7001/eureka/,http://myeureka7002.com:7002/eureka/ #??? Eureka Server ??? 7001 ? 7002 ?