server:
  port: 9527  #???
spring:
  application:
    name: microServiceCloudGateway
  cloud:
    gateway: #??????
      routes:
        #? micro-service-cloud-provider-dept-8001 ????????????????????????? API ????? 9527
        - id: provider_dept_list_routh   #?? id,???????????????????
          # uri: http://localhost:8001          #????????????
          uri: lb://MICROSERVICECLOUDPROVIDERDEPT #????????????????????   http://myeureka7001.com:9527/dept/list
          predicates:
            #????????????????
            - Path=/dept/list/**               #??????? ???Path ? P ???
            - Method=GET #??? GET ????????
          # predicates:
          #  - Path=/get/**
          # filters:
          #    - PrefixPath=/dept #???????????? /dept

eureka:
  instance:
    instance-id: micro-service-cloud-gateway-9527
    hostname: micro-service-cloud-gateway
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://myeureka7001.com:7001/eureka/,http://myeureka7002.com:7002/eureka/,http://myeureka7003.com:7003/eureka/